# -*- coding: utf-8 -*-
"""acme_report

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gfdblq2iRsflEAbtC7aOJj7YAarStzWL
"""

def generate_products(x=30):
  cart = []
  for _ in range(x):
    adjective = random.choice(['Awesome', 'Shiny', 'Impressive',
                               'Portable', 'Improved'])
    noun = random.choice(['Anvil', 'Catapult' 'Disguise' 'Mousetrap', '???'])
    acme_name = f'{adjective} {noun}'
    price = random.randint(5, 100)
    weight = random.randint(5, 100)
    flammability = random.uniform(0.0, 2.5)
    cart.append(Product(acme_name, price, weight, flammability))
  return cart

def inventory_report(x):
  names_list = [prod.acme_name for prod in x]
  names_total = len(list(set(names_list)))
  price_list = [prod.price for prod in x]
  price_avg = sum(price_list) / len(price_list)
  weight_list = [prod.weight for prod in x]
  weight_avg = sum(weight_list) / len(weight_list)
  flammy_list = [prod.flammability for prod in x]
  flammy_avg = sum(flammy_list) / len(flammy_list)
  print("ACME CORP. OFFICIAL INVENTORY REPORT")
  print("Unique product names:", {names_total})
  print("Average price:", {price_avg})
  print("Average weight:", {weight_avg})
  print ("Average flammability:", {flammy_avg})

  if __name__ == '__main__':
    inventory_report(generate_products())