# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L1pjnvrO8Oaw1v2oosGPgMvs4ZncLDS6
"""

import unittest
import random

class Product():
  def __init__ (self, Name, Price = 10, Weight = 20, Flammability = '0.5'):
    self.Name = Name 
    self.Price = int(Price)
    self.Weight = int(Weight)
    self.Flammability = float(Flammability)
    self.Identifier = int(random.randint(1000000, 9999999))

  def stealability(self):
    x = self.Price / self.Weight
    if x < 0.5:
      return "Not so stealable"
    if x >= 0.5 and x > 1.0:
      return "Kinda stealable"
    else:
      return "Warning: Very stealable!"


  def explode(self):
    x = self.Flammability * self.Weight
    if x < 10:
      return "...fizzle"
    if x >= 10 and x < 50:
      return "....boom!"
    else:
      return "...BABOOM!"


class BoxingGlove(Product):
  def __init__ (self, Name, Price = 10, Weight = 10, Flammability = '0.5'):
    super().__init__(Name, Price, Weight, Flammability)

  def explode(self):
    return "...it's a glove"

  def punch(self):
    x = self.Weight
    if x < 5:
      return "That tickles."
    if x >= 5 and x < 15:
      return "Hey that hurt!"
    else: 
      return "Ouch!"

